[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]

[project]
name = "matricidadde"
version = "0.0.1"
dependencies = [
    "numpy"
]


[tool.setuptools_scm]
write_to = "_version.py"
