name: build

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip 
          pip --version

      - name: install package and run it (should print package version)
        run: |
          pip install .
          example-main
