name: Release

on:
  release:
    types: [published]

  workflow_dispatch:

env:
  FORCE_COLOR: "1"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          pip install --upgrade pip
          pip --version

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Install built package and run it
        run: |
          pip install dist/setuptools*whl
          example-main
